name: cuponi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.5.0+1
  google_fonts: ^6.2.1
  new_version_plus: ^0.0.11
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  firebase_auth: ^5.1.2
  flutter_facebook_auth: ^6.0.4
  flutter_rating_bar: ^4.0.1
  range_slider_flutter: ^0.0.2
  dotted_border: ^2.1.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/lottiefiles/

